from dataclasses import dataclass

"""
Only store color values.
There are no functions.

Only data.
"""

@dataclass(frozen=True)
class ThemeColors:

    # Primary
    PRIMARY: str
    PRIMARY_HOVER: str
    PRIMARY_PRESSED: str

    # Secondary
    SECONDARY: str  
    SECONDARY_HOVER: str
    SECONDARY_PRESSED: str
    SECONDARY_TEXT: str

    #QUICK ACCESS
    QUICK_ACCESS_BACKGROUND: str
    QUICK_ACCESS_HOVER: str
    QUICK_ACCESS_PRESSED: str
    QUICK_ACCESS_TEXT: str
    

    # Status
    SUCCESS: str
    WARNING: str
    DANGER: str

    BUTTON_DISABLED: str
    BUTTON_DISABLED_TEXT: str
    BUTTON_DISABLED_BORDER: str

    # Background
    WINDOW: str
    PANEL: str

    # Border
    BORDER: str

    # Text
    TEXT: str
    TEXT_INVERT: str

    # Table
    TABLE_HEADER: str
    TABLE_ROW: str
    TABLE_ROW_ALT: str
    TABLE_GRID: str
    TABLE_SELECTION: str
    TABLE_HOVER: str

    SCROLLBAR: str
    SCROLLBAR_HOVER: str

    SWITCH_ON: str
    SWITCH_OFF: str
    SWITCH_THUMB: str

LIGHT_COLORS = ThemeColors(

    PRIMARY="#0078D4",
    PRIMARY_HOVER="#2899F5",
    PRIMARY_PRESSED="#005A9E",

    SECONDARY="#E1E1E1",
    SECONDARY_HOVER="#D1D1D1",  
    SECONDARY_PRESSED="#B0B0B0",
    SECONDARY_TEXT="#444444",

    #QUICK ACCESS
    QUICK_ACCESS_BACKGROUND = "#2D92DF",
    QUICK_ACCESS_HOVER = "#1C6FB5",
    QUICK_ACCESS_PRESSED = "#0D4C8A",
    QUICK_ACCESS_TEXT = "#FFFFFF",

    SUCCESS="#2E8B57",
    WARNING="#E67E22",
    DANGER="#C0392B",

    BUTTON_DISABLED         = "#E5E7EB",
    BUTTON_DISABLED_TEXT    = "#9CA3AF",
    BUTTON_DISABLED_BORDER  = "#D1D5DB",

    WINDOW="#FFFFFF",
    PANEL="#F6F8FA",

    BORDER="#D9D9D9",

    TEXT="#202020",
    TEXT_INVERT="#FFFFFF",

    TABLE_HEADER="#EFEFEF",

    TABLE_ROW="#FFFFFF",
    TABLE_ROW_ALT="#DADADA",

    TABLE_GRID="#D9D9D9",

    TABLE_SELECTION="#A4CBE9",

    TABLE_HOVER="#9AC1F4",

    SCROLLBAR="#BDBDBD",
    SCROLLBAR_HOVER="#8C8C8C",

    SWITCH_ON="#34C759",
    SWITCH_OFF="#C7C7CC",
    SWITCH_THUMB="#FFFFFF",
)

DARK_COLORS = ThemeColors(

    PRIMARY="#4CC2FF",
    PRIMARY_HOVER="#70D1FF",
    PRIMARY_PRESSED="#008ECC",

    SECONDARY="#3A3A3A",
    SECONDARY_HOVER="#4A4A4A",  
    SECONDARY_PRESSED="#5A5A5A",
    SECONDARY_TEXT="#444444",

    #QUICK ACCESS
    QUICK_ACCESS_BACKGROUND = "#4DA6EB",
    QUICK_ACCESS_HOVER = "#2D92DF",
    QUICK_ACCESS_PRESSED = "#1C6FB5",
    QUICK_ACCESS_TEXT = "#ECE7E7",

    BUTTON_DISABLED         = "#3A3A3A",
    BUTTON_DISABLED_TEXT    = "#7D7D7D",
    BUTTON_DISABLED_BORDER  = "#4A4A4A",

    SUCCESS="#3CB371",
    WARNING="#F4A261",
    DANGER="#FF6B6B",

    WINDOW="#202124",
    PANEL="#2B2B2B",

    BORDER="#444444",

    TEXT="#F2F2F2",
    TEXT_INVERT="#FFFFFF",

    TABLE_HEADER="#333333",

    TABLE_ROW="#202124",
    TABLE_ROW_ALT="#121316",

    TABLE_GRID="#444444",

    TABLE_SELECTION="#4CC2FF",

    TABLE_HOVER="#4CC2FF",

    SCROLLBAR="#666666",
    SCROLLBAR_HOVER="#AAAAAA",

    SWITCH_ON="#30D158",
    SWITCH_OFF="#555555",
    SWITCH_THUMB="#FFFFFF",

)